name: cli
description: A tool to help with maintaining the package.

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  cli_util: ^0.4.2
  args: ^2.6.0
  io: ^1.0.5
  yaml_edit: ^2.2.2
  yaml: ^3.1.3
  toml: ^0.16.0

dev_dependencies:
  lints: ^5.1.1
