name: cli
description: A tool to help with maintaining the package.

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

executables:
  cli: bin/cli.dart

dependencies:
  args: ^2.6.0
  io: ^1.0.5
  yaml_edit: ^2.2.2
  yaml: ^3.1.3
  toml: ^0.16.0
  mason_logger: ^0.3.2
  github: ^9.24.0
  collection: ^1.19.0
  pub_updater: ^0.5.0

dev_dependencies:
  lints: ^5.1.1
