name: cli
description: A tool to help with maintaining the package.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cli_util: ^0.4.2
  args: ^2.6.0
  io: ^1.0.5

dev_dependencies:
  lints: ^5.1.1
