# This file is a part of simple_audio
# Copyright (c) 2022-2023 Erikas Taroza <erikastaroza@gmail.com>
#
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

name: Publish

on:
  release:
    types: [created]

jobs:
  build_and_upload:
    name: Build and Upload Artifacts
    strategy:
      matrix:
        include:
          - target: linux
            os: ubuntu-20.04
            path: simple_audio_flutter/linux/libsimple_audio_flutter.so
          - target: android
            os: ubuntu-latest
            path: |
              simple_audio_flutter/android/src/main/jniLibs/arm64-v8a/libsimple_audio_flutter.so
              simple_audio_flutter/android/src/main/jniLibs/armeabi-v7a/libsimple_audio_flutter.so
              simple_audio_flutter/android/src/main/jniLibs/x86_64/libsimple_audio_flutter.so
              simple_audio_flutter/android/src/main/jniLibs/x86/libsimple_audio_flutter.so
          - target: windows
            os: windows-latest
            path: simple_audio_flutter/windows/simple_audio_flutter.dll
          - target: macos
            os: macos-latest
            path: simple_audio_flutter/macos/Libs/libsimple_audio_flutter.a
          - target: ios
            os: macos-latest
            path: simple_audio_flutter/ios/Frameworks/simple_audio_flutter.xcframework
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: ./.github/actions/setup_build
      - name: Install Rust -sys dependencies
        if: ${{ matrix.target == 'linux' }}
        run: |
          sudo apt install libasound2-dev

      - name: Build
        run: python ./plugin_tool.py -b ${{ matrix.target }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.path }}

  publish_to_release:
    name: Publish Artifacts to Release
    needs: build_and_upload
    runs-on: ubuntu-latest
    steps:
      # Downloading unzips the artifacts so they have to be rezipped.
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Create Archives
        run: |
          tar -C linux -czvf linux.tar.gz .
          tar -C android -czvf android.tar.gz .
          tar -C windows -czvf windows.tar.gz .
          zip -j macos.zip macos/*
          cd ios && zip -r ios.zip ./* && cd .. && mv ios/ios.zip .
      - name: Add to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux.tar.gz
            android.tar.gz
            windows.tar.gz
            macos.zip
            ios.zip
